// File generated by FlutterFire CLI.
// This file should be generated by running: flutterfire configure
// For now, this is a placeholder. Run the command to generate proper configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:287339191729:web:your_web_app_id',
    messagingSenderId: '287339191729',
    projectId: 'skilllink-fd388',
    authDomain: 'skilllink-fd388.firebaseapp.com',
    storageBucket: 'skilllink-fd388.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxqqr0qDuWZVyCxZmudlF4E6wMQUoBDD0',
    appId: '1:287339191729:android:8624f0707fd2929460f190',
    messagingSenderId: '287339191729',
    projectId: 'skilllink-fd388',
    storageBucket: 'skilllink-fd388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:287339191729:ios:your_ios_app_id',
    messagingSenderId: '287339191729',
    projectId: 'skilllink-fd388',
    storageBucket: 'skilllink-fd388.firebasestorage.app',
    iosBundleId: 'com.skilllink.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:287339191729:ios:your_macos_app_id',
    messagingSenderId: '287339191729',
    projectId: 'skilllink-fd388',
    storageBucket: 'skilllink-fd388.firebasestorage.app',
    iosBundleId: 'com.skilllink.app',
  );
}


