// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWWgUt7sVX0t0ylr6DwpEk9o_3UuFcNDk',
    appId: '1:287339191729:web:ce3ff2fccc520e6f60f190',
    messagingSenderId: '287339191729',
    projectId: 'skilllink-fd388',
    authDomain: 'skilllink-fd388.firebaseapp.com',
    storageBucket: 'skilllink-fd388.firebasestorage.app',
    measurementId: 'G-RLRPBBV472',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxqqr0qDuWZVyCxZmudlF4E6wMQUoBDD0',
    appId: '1:287339191729:android:8624f0707fd2929460f190',
    messagingSenderId: '287339191729',
    projectId: 'skilllink-fd388',
    storageBucket: 'skilllink-fd388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-NrFb5vDi0di4cR4BGXk9anEyOoBzqU',
    appId: '1:287339191729:ios:250c4e961c30769960f190',
    messagingSenderId: '287339191729',
    projectId: 'skilllink-fd388',
    storageBucket: 'skilllink-fd388.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg-NrFb5vDi0di4cR4BGXk9anEyOoBzqU',
    appId: '1:287339191729:ios:250c4e961c30769960f190',
    messagingSenderId: '287339191729',
    projectId: 'skilllink-fd388',
    storageBucket: 'skilllink-fd388.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWWgUt7sVX0t0ylr6DwpEk9o_3UuFcNDk',
    appId: '1:287339191729:web:bb9d7375765e81d760f190',
    messagingSenderId: '287339191729',
    projectId: 'skilllink-fd388',
    authDomain: 'skilllink-fd388.firebaseapp.com',
    storageBucket: 'skilllink-fd388.firebasestorage.app',
    measurementId: 'G-CHWNJYDNSD',
  );
}
