import '../models/worker.dart';
import '../models/job.dart';

class SampleData {
  static List<Worker> workers = [
    Worker(
      id: '1',
      name: 'John Smith',
      email: 'john@example.com',
      phone: '+1234567890',
      profileImage: 'https://ui-avatars.com/api/?name=John+Smith&background=2563EB&color=fff',
      hourlyRate: 50.0,
      description: 'Certified electrician with 10+ years experience. Specialized in residential and commercial electrical work.',
      rating: 4.8,
      totalJobs: 156,
      skills: ['Wiring', 'Panel Installation', 'Circuit Repair', 'Lighting'],
      location: 'New York, NY',
      isAvailable: true,
      level: WorkerLevel.expert,
      yearsOfExperience: 10,
      completedProjects: 156,
      successRate: 98.5,
      portfolio: [],
      reviews: [
        Review(
          userId: 'u1',
          userName: 'Sarah Johnson',
          rating: 5.0,
          comment: 'Excellent work! Very professional and finished on time.',
          date: DateTime.now().subtract(const Duration(days: 5)),
        ),
      ],
    ),
    Worker(
      id: '2',
      name: 'Mike Johnson',
      email: 'mike@example.com',
      phone: '+1234567891',
      profileImage: 'https://ui-avatars.com/api/?name=Mike+Johnson&background=10B981&color=fff',
      hourlyRate: 45.0,
      description: 'Expert plumber for all your plumbing needs. Fast, reliable, and affordable.',
      rating: 4.9,
      totalJobs: 203,
      skills: ['Pipe Repair', 'Drain Cleaning', 'Water Heater', 'Leak Detection'],
      location: 'Los Angeles, CA',
      isAvailable: true,
      level: WorkerLevel.expert,
      yearsOfExperience: 8,
      completedProjects: 203,
      successRate: 99.2,
      portfolio: [],
      reviews: [],
    ),
    Worker(
      id: '3',
      name: 'David Wilson',
      email: 'david@example.com',
      phone: '+1234567892',
      profileImage: 'https://ui-avatars.com/api/?name=David+Wilson&background=EF4444&color=fff',
      hourlyRate: 55.0,
      description: 'Experienced auto mechanic. All makes and models. Quality service guaranteed.',
      rating: 4.7,
      totalJobs: 178,
      skills: ['Engine Repair', 'Brake Service', 'Oil Change', 'Diagnostics'],
      location: 'Chicago, IL',
      isAvailable: true,
      level: WorkerLevel.professional,
      yearsOfExperience: 12,
      completedProjects: 178,
      successRate: 96.5,
      portfolio: [],
      reviews: [],
    ),
    Worker(
      id: '4',
      name: 'Robert Brown',
      email: 'robert@example.com',
      phone: '+1234567893',
      profileImage: 'https://ui-avatars.com/api/?name=Robert+Brown&background=92400E&color=fff',
      hourlyRate: 48.0,
      description: 'Custom woodworking and carpentry. Furniture repair and installation specialist.',
      rating: 4.6,
      totalJobs: 134,
      skills: ['Furniture Assembly', 'Custom Cabinets', 'Door Installation', 'Deck Building'],
      location: 'Houston, TX',
      isAvailable: false,
      level: WorkerLevel.professional,
      yearsOfExperience: 7,
      completedProjects: 134,
      successRate: 95.0,
      portfolio: [],
      reviews: [],
    ),
    Worker(
      id: '5',
      name: 'James Martinez',
      email: 'james@example.com',
      phone: '+1234567894',
      profileImage: 'https://ui-avatars.com/api/?name=James+Martinez&background=8B5CF6&color=fff',
      hourlyRate: 40.0,
      description: 'Professional painting services. Interior and exterior painting with attention to detail.',
      rating: 4.8,
      totalJobs: 167,
      skills: ['Interior Painting', 'Exterior Painting', 'Wall Preparation', 'Color Consulting'],
      location: 'Phoenix, AZ',
      isAvailable: true,
      level: WorkerLevel.professional,
      yearsOfExperience: 5,
      completedProjects: 167,
      successRate: 97.8,
      portfolio: [],
      reviews: [],
    ),
    Worker(
      id: '6',
      name: 'Ali Hassan',
      email: 'ali@example.com',
      phone: '+1234567895',
      profileImage: 'https://ui-avatars.com/api/?name=Ali+Hassan&background=F59E0B&color=fff',
      hourlyRate: 25.0,
      description: 'Custom tailoring and alterations. Traditional and modern designs.',
      rating: 4.2,
      totalJobs: 45,
      skills: ['Stitching', 'Alterations', 'Custom Design', 'Embroidery'],
      location: 'Karachi, Pakistan',
      isAvailable: true,
      level: WorkerLevel.newbie,
      yearsOfExperience: 2,
      completedProjects: 45,
      successRate: 92.0,
      portfolio: [],
      reviews: [],
    ),
  ];

  static List<Job> getWorkerJobs(String workerId) {
    return [
      Job(
        id: 'j1',
        workerId: workerId,
        workerName: 'John Smith',
        userId: 'u1',
        userName: 'Sarah Johnson',
        category: 'Electrician',
        description: 'Need to fix electrical outlets in living room',
        location: 'New York, NY',
        scheduledDate: DateTime.now().add(const Duration(days: 2)),
        estimatedHours: 3,
        hourlyRate: 50.0,
        status: JobStatus.pending,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      Job(
        id: 'j2',
        workerId: workerId,
        workerName: 'John Smith',
        userId: 'u2',
        userName: 'Mike Davis',
        category: 'Electrician',
        description: 'Install new ceiling fan',
        location: 'Brooklyn, NY',
        scheduledDate: DateTime.now().add(const Duration(days: 5)),
        estimatedHours: 2,
        hourlyRate: 50.0,
        status: JobStatus.accepted,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
    ];
  }

  static List<Job> getUserJobs(String userId) {
    return [
      Job(
        id: 'j3',
        workerId: 'w1',
        workerName: 'John Smith',
        userId: userId,
        userName: 'Current User',
        category: 'Electrician',
        description: 'Install outdoor lighting',
        location: 'New York, NY',
        scheduledDate: DateTime.now().add(const Duration(days: 3)),
        estimatedHours: 4,
        hourlyRate: 50.0,
        status: JobStatus.inProgress,
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
      ),
    ];
  }
}


